### ISSUE TITLE
dap-debug cannot run flutter app as expected

### ISSUE THREAD

**Issue by gcanoxl** [emacs-lsp/lsp-dart#109] opened 2021-08-01 19:56 UTC
**Describe the bug**
After run `dap-debug`, `Flutter :: Debug` and `ios - emulator - iOS Simulator`。It starts the simulator successfully and doesn't work any more.  There is no any app(apart from built-in ones) on iOS Simulator device to run. And there is no any error message.

I **had already** tried to remove `.extension` folder and then executed `lsp-dart-dap-setup` again and again, but it ** still** didn't work.

there's the contents in `*LSP Dart - Flutter daemon*`
```
[{"event":"daemon.connected","params":{"version":"0.6.0","pid":23361}}]
[{"event":"daemon.logMessage","params":{"level":"status","message":"Starting device daemon..."}}]
[{"id":28539}]
[{"id":95626,"result":[{"id":"apple_ios_simulator","name":"iOS Simulator","category":"mobile","platformType":"ios"}]}]
[{"event":"device.added","params":{"id":"chrome","name":"Chrome","platform":"web-javascript","emulator":false,"category":"web","platformType":"web","ephemeral":false,"emulatorId":null}}]
[{"event":"device.added","params":{"id":"AAD5F255-0DFD-4CB4-9035-13599DB6F1E2","name":"iPhone 12 Pro Max","platform":"ios","emulator":true,"category":"mobile","platformType":"ios","ephemeral":true,"emulatorId":"apple_ios_simulator"}}]

```

**To Reproduce**
 run `dap-debug`, `Flutter :: Debug` and `ios - emulator - iOS Simulator`.

**Expected behavior**
It should automatically run the program on the simulator device.

**Version**
![image](https://user-images.githubusercontent.com/26963009/127783598-dd3022a2-a54c-485b-9940-7562366662d8.png)

**Comment by ericdallo** [comment] 2021-08-01 20:06
thank you for the report, I can't test the IOS simulator, could you check if that happens for android devices or is this something an IOS thing?

**Comment by gcanoxl** [comment] 2021-08-02 03:57
Oh, I tested the web program, and the error result is 
![image](https://user-images.githubusercontent.com/26963009/127802449-e3dffcfa-4a1b-43f4-9780-96878b84d749.png)
As for android device, I'll be trying to test.

**Comment by gcanoxl** [comment] 2021-08-02 04:17
Sorry, the previous error caused by my wrong environment. I've fixed it by running Emacs from shell.

There's the error message when I tried to run the program on Web.
![image](https://user-images.githubusercontent.com/26963009/127803583-8452a021-fa7e-4872-be21-9544efecbb94.png)

And there's the error message when I tried to run the program on my Phone.(not simulator)
![image](https://user-images.githubusercontent.com/26963009/127803634-dcb95d1e-62e3-47f8-a0a7-023440de07ab.png)

**Comment by ericdallo** [comment] 2021-08-02 12:41
The later one seems that you didn't accept the APK installation in the range of 10s.

**Comment by gcanoxl** [comment] 2021-08-02 13:34
> The later one seems that you didn't accept the APK installation in the range of 10s.

Yes, you're right.

After I had turned that option on my phone,  I could use `flutter run` in shell to run the program on the phone. But when I tried to use `dap-debug` to run, it still didn't work. 

![image](https://user-images.githubusercontent.com/26963009/127869839-3c75764e-e288-4f97-9895-d019d8f6367f.png)
As the screenshot shows, it always stops at `Installing.....xx/app.apk`

And the app had been installed, but unfortunately, the whole app was white screen

**Comment by ericdallo** [comment] 2021-08-02 13:37
Hum, Could you try [this sample project](https://github.com/ericdallo/flutter_sample)? Oterwise I'll need to deep dive and understand how/test on my side

**Comment by gcanoxl** [comment] 2021-08-02 14:39
While I use your sample project, the situation is

![image](https://user-images.githubusercontent.com/26963009/127879121-7e7f0938-270e-4354-8c05-acf81c230df6.png)

**Comment by gcanoxl** [comment] 2021-08-02 14:42
While I was using your sample project, the situation is 
![image](https://user-images.githubusercontent.com/26963009/127879581-ed451e88-829b-4de8-8fef-ff9a317a9c85.png)

**Comment by gcanoxl** [comment] 2021-08-02 14:43
Here's the full contents in `*Flutter :: Debug<1> out*`

```
Error: Couldn't resolve the package 'linear_progress_loading' in 'package:linear_progress_loading/linear_progress_loading.dart'.
lib/screens/dashboard/components/leftscreen.dart:2:8: Error: Not found: 'package:linear_progress_loading/linear_progress_loading.dart'
import 'package:linear_progress_loading/linear_progress_loading.dart';
       ^

lib/screens/dashboard/components/leftscreen.dart:9:9: Error: The getter 'LinearProgressLoading' isn't defined for the class 'LeftScreen'.
 - 'LeftScreen' is from 'package:flutter_sample/screens/dashboard/components/leftscreen.dart' ('lib/screens/dashboard/components/leftscreen.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'LinearProgressLoading'.
        LinearProgressLoading.trickling(
        ^^^^^^^^^^^^^^^^^^^^^
Unhandled exception:
FileSystemException(uri=org-dartlang-untranslatable-uri:package%3Alinear_progress_loading%2Flinear_progress_loading.dart; message=StandardFileSystem only supports file:* and data:* URIs)
#0      StandardFileSystem.entityForUri (package:front_end/src/api_prototype/standard_file_system.dart:36:7)

#1      asFileUri (package:vm/kernel_front_end.dart:599:37)
#2      writeDepfile (package:vm/kernel_front_end.dart:738:21)
<asynchronous suspension>
#3      FrontendCompiler.compile (package:frontend_server/frontend_server.dart:562:9)
<asynchronous suspension>
#4      starter (package:flutter_frontend_server/server.dart:180:12)

<asynchronous suspension>
#5      main (file:///opt/s/w/ir/cache/builder/src/flutter/flutter_frontend_server/bin/starter.dart:13:24)
<asynchronous suspension>




FAILURE: Build failed with an exception.

* Where:
Script '/usr/local/Caskroom/flutter/2.2.3/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 1035

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command '/usr/local/Caskroom/flutter/2.2.3/flutter/bin/flutter'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 5m 11s
Exception: Gradle task assembleDebug failed with exit code 1
```

**Comment by ericdallo** [comment] 2021-08-02 14:57
Oh my bad, the project was using a local package, I commented and made a commit, can you check again?

**Comment by ericdallo** [comment] 2021-08-02 15:09
Alright, so it doesn't work for your phisical phone as well? so it must be some kind of bug with some recent flutter/dark sdk version. I'l ltry to reproduce it later today

**Comment by gcanoxl** [comment] 2021-08-02 15:17
thank you very very very much!!! 
If you need my help, I will help you as possible as I can!

**Comment by ericdallo** [comment] 2021-08-02 23:03
@gcanoxl Everything worked fine for my sample project, one thing I forgot to mention is that the first screen was really white 🤦🏻‍♂️ , so I updated it making the first screen another one, could you test it again? 
I tested using the same flutter as yours on an android device

**Comment by gcanoxl** [comment] 2021-08-03 06:24
Oh my god!! I've solved all the problem by add ` export NO_PROXY=localhost,127.0.0.1` into `.zshrc` and `.bash_profile`. 
It can run well on all devices(both iOS simulator and my real android phone).

I don't know why it has to be, but fortunately all problems have been solved now!

By the way, I think you should add my situation into FAQ section lest many other nobles run into the same problem.

**Comment by gcanoxl** [comment] 2021-08-03 06:27
Last but not least, Thanks for your patience, hope your project grows well!

**Comment by ericdallo** [comment] 2021-08-03 12:33
Cool! Would you mind opening a PR adding that to the FAQ?

**Comment by gcanoxl** [comment] 2021-08-03 17:51
Actually... I don't know when it has to be and why it has to be.... I'm not sure if I could write the FAQ well.....

**Comment by ericdallo** [comment] 2021-08-03 17:59
Maybe we can add something linking to https://github.com/flutter/flutter/issues/24854?

**Comment by gcanoxl** [comment] 2021-08-03 18:18
Yes, we should! Maybe we can write:

```
If you run into some problems about debugging, try to check your proxy settings, (and then, a link to that issue or this issue).
```

By the way, for now, I'm being suffered another problem, 
![image](https://user-images.githubusercontent.com/26963009/128065623-6350b3e1-386b-4890-b46d-7434a1b0e4bf.png)
After I had typed Enter, the cursor would be after the comma. I must delete the comma and then write codes. 
Why shouldn't the cursor be before the comma?
![image](https://user-images.githubusercontent.com/26963009/128065649-a5c608e0-2ce3-469c-b393-c937a4220670.png)

**Comment by ericdallo** [comment] 2021-08-03 18:25
> Yes, we should! Maybe we can write:

LGTM

> Why shouldn't the cursor be before the comma?

This actually works to me 🤔 
![completion-lsp-dart](https://user-images.githubusercontent.com/7820865/128066984-4c06b209-76aa-4503-bc02-c526aa090fc1.gif)

**Comment by gcanoxl** [comment] 2021-08-03 18:45
> LGTM
What does it mean???

> This actually works to me 🤔
Could you show me your `lsp-dart-version`? or do you know why the problem happens to me?

**Comment by ericdallo** [comment] 2021-08-03 19:01
> What does it mean???

Looks good to me :)

> Could you show me your lsp-dart-version? or do you know why the problem happens to me?

```
[LSP Dart] 1.19.1 at 2021.08.03 @ Emacs 28.0.50
[Dart SDK] Dart SDK version: 2.13.4 (stable) (Wed Jun 23 13:08:41 2021 +0200) on "linux_x64"

[Flutter SDK] /home/greg/flutter
[Flutter project] true
[Project entrypoint] Not found
```

Not sure why, but it seems related with lsp-mode, maybe open an issue there?

**Comment by gcanoxl** [comment] 2021-08-03 19:11
But why did it work well on your machine....What configuration do you use about lsp-mode?

**Comment by ericdallo** [comment] 2021-08-03 19:15
This is my config: https://github.com/ericdallo/dotfiles/blob/master/.doom.d/config.el#L152-L179 but I don't think it's related with that issue :/

**Comment by gcanoxl** [comment] 2021-08-03 19:19
You're right... I couldn't find something helpful in your config. Maybe I'll have to open an issue there. (omg)

**Comment by ericdallo** [comment] 2021-08-03 19:25
I'm closing this one and I'll update the FAQ soon, feel free to open a new issue there

**Closed by ericdallo** 2021-08-03 19:25 UTC

**Comment by zw963** [comment] 2022-01-01 05:36
I am so tired of why dap-debug not work with my config, @ericdallo , could you please share a one file .emacs config (use packet mananger if need), which i can try if i can reproduce it on my local ?

Thank you.

**Comment by zw963** [comment] 2022-01-01 06:01
Following is my error output:

```
adb: failed to install /home/zw963/Magpie/magpie-mobile-app/build/app/outputs/flutter-apk/app.apk: cmd: Can't find service: package
Error launching application on Xiaomi Redmi Note 7.
Process terminated! null, SIGTERM
```

following is my debug output:

```
[{"event":"daemon.connected","params":{"version":"0.6.1","pid":47251}}]
[{"event":"daemon.logMessage","params":{"level":"status","message":"Starting device daemon..."}}]
[{"id":41170}]
[{"event":"device.added","params":{"id":"chrome","name":"Chrome","platform":"web-javascript","emulator":false,"category":"web","platformType":"web","ephemeral":false,"emulatorId":null}}]
[{"event":"device.added","params":{"id":"192.168.56.104:5555","name":"Xiaomi Redmi Note 7","platform":"android-x86","emulator":false,"category":"mobile","platformType":"android","ephemeral":true,"emulatorId":null}}]
[{"id":5526,"result":[]}]
[{"event":"daemon.logMessage","params":{"level":"error","message":"Error 1 retrieving device properties for Xiaomi Redmi Note 7:"}}]
[{"event":"daemon.logMessage","params":{"level":"error","message":"adb: device offline\n"}}]
[{"event":"device.removed","params":{"id":"192.168.56.104:5555","name":"Xiaomi Redmi Note 7","platform":"android-arm","emulator":false,"category":"mobile","platformType":"android","ephemeral":true,"emulatorId":null}}]
[{"event":"device.added","params":{"id":"192.168.56.104:5555","name":"Xiaomi Redmi Note 7","platform":"android-x86","emulator":false,"category":"mobile","platformType":"android","ephemeral":true,"emulatorId":null}}]
[{"event":"daemon.logMessage","params":{"level":"error","message":"Error 1 retrieving device properties for Xiaomi Redmi Note 7:"}}]
[{"event":"daemon.logMessage","params":{"level":"error","message":"adb: device '192.168.56.104:5555' not found\n"}}]
[{"event":"device.removed","params":{"id":"192.168.56.104:5555","name":"Xiaomi Redmi Note 7","platform":"android-arm","emulator":false,"category":"mobile","platformType":"android","ephemeral":true,"emulatorId":null}}]
[{"event":"device.added","params":{"id":"192.168.56.104:5555","name":"Xiaomi Redmi Note 7","platform":"android-x86","emulator":false,"category":"mobile","platformType":"android","ephemeral":true,"emulatorId":null}}]
[{"id":60692,"result":[]}]
```

Following is emacs error output:

```
Debugger entered--Lisp error: (args-out-of-range 619 1 608)
  #<subr F616e6f6e796d6f75732d6c616d626461_anonymous_lambda_67>((:point 619))
  -map(#<subr F616e6f6e796d6f75732d6c616d626461_anonymous_lambda_67> ((:point 619)))
  dap--set-breakpoints-request("/home/zw963/Stocks/marketbet_crawler/config/hot_re..." ((:point 619)))
  #f(compiled-function (file-name file-breakpoints) #<bytecode -0x19d866c55c81d9ea>)("/home/zw963/Stocks/marketbet_crawler/config/hot_re..." ((:point 619)))
  dap--configure-breakpoints(#s(dap--debug-session :name "Flutter :: Debug" :last-id 7 :proc #<process Flutter :: Debug> :response-handlers #<hash-table eql 4/65 0x1580d0892c1f> :parser #s(dap--parser :waiting-for-response nil :response-result nil :headers nil :body nil :reading-body nil :body-length nil :body-received nil :leftovers "") :output-buffer #<buffer *Flutter :: Debug out*> :thread-id nil :workspace nil :threads (#<hash-table equal 2/65 0x1580d110cedb>) :thread-states #<hash-table eql 1/65 0x1580d0892ddd> :active-frame-id nil :active-frame nil :cursor-marker nil :state pending :breakpoints #<hash-table equal 0/65 0x1580d0892dfd> :thread-stack-frames #<hash-table eql 0/65 0x1580d0892e1d> :launch-args (:name "Flutter :: Debug" :type "flutter" :request "launch" :dartSdkPath "/home/zw963/flutter/bin/cache/dart-sdk/" :maxLogLineLength 2000 :cwd "/home/zw963/Magpie/magpie-mobile-app/" :vmAdditionalArgs "" :vmServicePort 0 :debugExternalLibraries nil :debugSdkLibraries nil :evaluateGettersInDebugViews t :evaluateToStringInDebugViews t :flutterSdkPath "/home/zw963/flutter/" :flutterTrackWidgetCreation t :useFlutterStructuredErrors t :useWriteServiceInfo t :debuggerHandlesPathsEverywhereForBreakpoints t :flutterMode "debug" :dap-server-path ("node" "/home/zw963/Dropbox/common/.emacs.d/plugins/dap-mo..." "flutter") :output-filter-function lsp-dart-dap--output-filter-function :program "/home/zw963/Magpie/magpie-mobile-app/lib/main_loca..." :deviceId "192.168.56.104:5555" :deviceName "Xiaomi Redmi Note 7" :flutterPlatform "default") :current-capabilities #<hash-table equal 10/65 0x1580d08952c5> :error-message nil :loaded-sources nil :program-proc nil :metadata #<hash-table eql 0/65 0x1580d08956cb> :output-displayed t) #<hash-table equal 10/65 0x1580cfd1e76d> #f(compiled-function (&rest args2) #<bytecode -0xae407609fff89dd>))
  dap--on-event(#s(dap--debug-session :name "Flutter :: Debug" :last-id 7 :proc #<process Flutter :: Debug> :response-handlers #<hash-table eql 4/65 0x1580d0892c1f> :parser #s(dap--parser :waiting-for-response nil :response-result nil :headers nil :body nil :reading-body nil :body-length nil :body-received nil :leftovers "") :output-buffer #<buffer *Flutter :: Debug out*> :thread-id nil :workspace nil :threads (#<hash-table equal 2/65 0x1580d110cedb>) :thread-states #<hash-table eql 1/65 0x1580d0892ddd> :active-frame-id nil :active-frame nil :cursor-marker nil :state pending :breakpoints #<hash-table equal 0/65 0x1580d0892dfd> :thread-stack-frames #<hash-table eql 0/65 0x1580d0892e1d> :launch-args (:name "Flutter :: Debug" :type "flutter" :request "launch" :dartSdkPath "/home/zw963/flutter/bin/cache/dart-sdk/" :maxLogLineLength 2000 :cwd "/home/zw963/Magpie/magpie-mobile-app/" :vmAdditionalArgs "" :vmServicePort 0 :debugExternalLibraries nil :debugSdkLibraries nil :evaluateGettersInDebugViews t :evaluateToStringInDebugViews t :flutterSdkPath "/home/zw963/flutter/" :flutterTrackWidgetCreation t :useFlutterStructuredErrors t :useWriteServiceInfo t :debuggerHandlesPathsEverywhereForBreakpoints t :flutterMode "debug" :dap-server-path ("node" "/home/zw963/Dropbox/common/.emacs.d/plugins/dap-mo..." "flutter") :output-filter-function lsp-dart-dap--output-filter-function :program "/home/zw963/Magpie/magpie-mobile-app/lib/main_loca..." :deviceId "192.168.56.104:5555" :deviceName "Xiaomi Redmi Note 7" :flutterPlatform "default") :current-capabilities #<hash-table equal 10/65 0x1580d08952c5> :error-message nil :loaded-sources nil :program-proc nil :metadata #<hash-table eql 0/65 0x1580d08956cb> :output-displayed t) #<hash-table equal 3/65 0x1580c7eb9039>)
  #f(compiled-function (m) #<bytecode 0x814d0ee5badff86>)("{\"seq\":41,\"type\":\"event\",\"event\":\"initialized\"}")
  mapc(#f(compiled-function (m) #<bytecode 0x814d0ee5badff86>) ("{\"seq\":40,\"type\":\"event\",\"event\":\"dart.progressEnd..." "{\"seq\":41,\"type\":\"event\",\"event\":\"initialized\"}" "{\"seq\":42,\"type\":\"event\",\"event\":\"dart.serviceRegi..." "{\"seq\":43,\"type\":\"event\",\"event\":\"dart.serviceRegi..." "{\"seq\":44,\"type\":\"event\",\"event\":\"dart.serviceRegi..." "{\"seq\":45,\"type\":\"event\",\"event\":\"dart.serviceRegi..." "{\"seq\":46,\"type\":\"event\",\"event\":\"dart.serviceRegi..." "{\"seq\":47,\"type\":\"event\",\"event\":\"dart.serviceRegi..."))
  #f(compiled-function (_ msg) #<bytecode -0xb66619c5c5571df>)(#<process Flutter :: Debug> "Content-Length: 83\15\n\15\n{\"seq\":40,\"type\":\"event\",\"ev...")
```

**Comment by zw963** [comment] 2022-01-01 15:01
> @zw963 that sounds like bad compiled dap-mode package to me, could you try reinstalling dap-mode?

I recompile all package yesterday, native .eln and .elc, all update, i checked dap-mode, i use newest master on github, with almost all dependency recent days, no luck.

**Comment by zw963** [comment] 2022-01-01 15:05
@ericdallo , BTW, i even download and install doom emacs, with your's personal config replaced, it seem like still not work when i start a flutter project, even, when i want to start send time, it raise a error, not work anymore.

![image](https://user-images.githubusercontent.com/549126/147853550-6a62f468-9e82-4cde-9019-885ffbf80d07.png)

**Comment by ericdallo** [comment] 2022-01-01 15:06
Hum, I saw this issue somewhere, I'll try to repro that after fixing https://github.com/emacs-lsp/lsp-dart/issues/126#issuecomment-1003503667

**Comment by ericdallo** [comment] 2022-01-01 15:52
I can't repro the issue on my Xiaomi Mi 9 @zw963, after running `lsp-dart-dap-setup` and `dap-debug`, I suspect your issue is related with that error log:
```
[{"event":"daemon.logMessage","params":{"level":"error","message":"Error 1 retrieving device properties for Xiaomi Redmi Note 7:"}}]
[{"event":"daemon.logMessage","params":{"level":"error","message":"adb: device offline\n"}}]
```

**Comment by zw963** [comment] 2022-01-01 16:06
> 

Okay, in fact, i use genymotion simulator, i will try again use your's config, to identify why dap-debug not work.

**Comment by zw963** [comment] 2022-01-01 16:53
Let me use your's config + arch linux's emacs git (emacs 29) try to reproduce this.

at first, i have to comment following two line to make your's config work, because both of them different error.


this maybe because a font missing.
![image](https://user-images.githubusercontent.com/549126/147855566-6f5ff404-d689-4ab1-b3e3-8f66457ab84a.png)

-------------------

this cause  following error

Error in private config: config.el, (error ad-deactivate: ‘enable-theme’ is not advised)

![image](https://user-images.githubusercontent.com/549126/147855572-5ac7bba8-08b4-4f97-993f-ab6ab4c4f78c.png)

both two config should not take effect lsp-dart dap, right?

@ericdallo , can i disable native comp for doom? because that maybe not suitable for debug issue.

**Comment by zw963** [comment] 2022-01-01 17:06
Hi, @ericdallo , i try your's config again.

it seem like not devices not exists issue, in fact, i connect my huawei phone directly for avoid issue.

![image](https://user-images.githubusercontent.com/549126/147855917-4931dedd-aed9-4309-b710-b1cb1cbc7701.png)

but still could not start correct use your's config + doom

```
 ╰─ $ HOME=/tmp/emacs /tmp/emacs/.emacs.d/bin/doom sync
> Executing 'doom sync' with Emacs 29.0.50 at 2022-01-02 01:00:15
  > Synchronizing your config with Doom Emacs...
    > Regenerating envvars file at "~/.emacs.d/.local/env"
      ✓ Successfully generated "~/.emacs.d/.local/env"
    > Installing packages...
      - No packages need to be installed
    > (Re)building packages...
      - No packages need rebuilding
    > Purging orphaned packages (for the emperor)...
      - No builds to purge
      - Skipping elpa packages
      - Skipping repos
      - Skipping regrafting
      - Skipping native bytecode
    > (Re)generating autoloads file...
      > Generating autoloads file...
      > Byte-compiling autoloads file...
      ✓ Generated .local/autoloads.29.0.50.elc
    - Restart Emacs or use 'M-x doom/reload' for changes to take effect
  ✓ Finished in 5.6092s
```



Debugger entered--Lisp error: (void-function lsp--matching-clients\?)
  lsp--matching-clients\?(#s(lsp--client :language-id nil :add-on? nil :new-connection (:connect #f(compiled-function (filter sentinel name environment-fn) #<bytecode -0xfb607dd3710b1db>) :test\? #f(compiled-function () #<bytecode 0x1ca56a57a6a3>)) :ignore-regexps nil :ignore-messages nil :notification-handlers #<hash-table equal 4/65 0x158b2b7ac725> :request-handlers #<hash-table equal 0/65 0x158b2b7ac9fb> :response-handlers #<hash-table eql 0/65 0x158b2b7aca1b> :prefix-function nil :uri-handlers #<hash-table equal 0/65 0x158b2b7ace05> :action-handlers #<hash-table equal 0/65 0x158b2b7ad20b> :major-modes nil :activation-fn #f(compiled-function (filename &optional _) #<bytecode 0x185b5ef3ae90e623>) :priority 1 :server-id dart_analysis_server :multi-root nil :initialization-options ((onlyAnalyzeProjectsWithOpenFiles) (suggestFromUnimportedLibraries . t) (closingLabels . t) (outline . t) (flutterOutline . t)) :semantic-tokens-faces-overrides nil :custom-capabilities ((experimental (snippetTextEdit . t))) :library-folders-fn #f(compiled-function (workspace) #<bytecode -0x47eed769c6d2838>) :before-file-open-fn nil :initialized-fn nil :remote? nil :completion-in-comments? nil :path->uri-fn nil :uri->path-fn nil :environment-fn nil :after-open-fn lsp-dart--activate-features :async-request-handlers #<hash-table equal 0/65 0x158b2b7ad22b> :download-server-fn nil :download-in-progress? nil :buffers nil :synchronize-sections nil))
  apply(lsp--matching-clients\? #s(lsp--client :language-id nil :add-on? nil :new-connection (:connect #f(compiled-function (filter sentinel name environment-fn) #<bytecode -0xfb607dd3710b1db>) :test\? #f(compiled-function () #<bytecode 0x1ca56a57a6a3>)) :ignore-regexps nil :ignore-messages nil :notification-handlers #<hash-table equal 4/65 0x158b2b7ac725> :request-handlers #<hash-table equal 0/65 0x158b2b7ac9fb> :response-handlers #<hash-table eql 0/65 0x158b2b7aca1b> :prefix-function nil :uri-handlers #<hash-table equal 0/65 0x158b2b7ace05> :action-handlers #<hash-table equal 0/65 0x158b2b7ad20b> :major-modes nil :activation-fn #f(compiled-function (filename &optional _) #<bytecode 0x185b5ef3ae90e623>) :priority 1 :server-id dart_analysis_server :multi-root nil :initialization-options ((onlyAnalyzeProjectsWithOpenFiles) (suggestFromUnimportedLibraries . t) (closingLabels . t) (outline . t) (flutterOutline . t)) :semantic-tokens-faces-overrides nil :custom-capabilities ((experimental (snippetTextEdit . t))) :library-folders-fn #f(compiled-function (workspace) #<bytecode -0x47eed769c6d2838>) :before-file-open-fn nil :initialized-fn nil :remote? nil :completion-in-comments? nil :path->uri-fn nil :uri->path-fn nil :environment-fn nil :after-open-fn lsp-dart--activate-features :async-request-handlers #<hash-table equal 0/65 0x158b2b7ad22b> :download-server-fn nil :download-in-progress? nil :buffers nil :synchronize-sections nil))
  #f(compiled-function (&rest args) #<bytecode -0xe399f76ee552373>)(#s(lsp--client :language-id nil :add-on? nil :new-connection (:connect #f(compiled-function (filter sentinel name environment-fn) #<bytecode -0xfb607dd3710b1db>) :test\? #f(compiled-function () #<bytecode 0x1ca56a57a6a3>)) :ignore-regexps nil :ignore-messages nil :notification-handlers #<hash-table equal 4/65 0x158b2b7ac725> :request-handlers #<hash-table equal 0/65 0x158b2b7ac9fb> :response-handlers #<hash-table eql 0/65 0x158b2b7aca1b> :prefix-function nil :uri-handlers #<hash-table equal 0/65 0x158b2b7ace05> :action-handlers #<hash-table equal 0/65 0x158b2b7ad20b> :major-modes nil :activation-fn #f(compiled-function (filename &optional _) #<bytecode 0x185b5ef3ae90e623>) :priority 1 :server-id dart_analysis_server :multi-root nil :initialization-options ((onlyAnalyzeProjectsWithOpenFiles) (suggestFromUnimportedLibraries . t) (closingLabels . t) (outline . t) (flutterOutline . t)) :semantic-tokens-faces-overrides nil :custom-capabilities ((experimental (snippetTextEdit . t))) :library-folders-fn #f(compiled-function (workspace) #<bytecode -0x47eed769c6d2838>) :before-file-open-fn nil :initialized-fn nil :remote? nil :completion-in-comments? nil :path->uri-fn nil :uri->path-fn nil :environment-fn nil :after-open-fn lsp-dart--activate-features :async-request-handlers #<hash-table equal 0/65 0x158b2b7ad22b> :download-server-fn nil :download-in-progress? nil :buffers nil :synchronize-sections nil))
  -filter(#f(compiled-function (&rest args) #<bytecode -0xe399f76ee552373>) (... ... ... ... ... ... ... ... ... ... ... ... ... ... ...))
  lsp--filter-clients(#f(compiled-function (&rest args) #<bytecode -0xe399f76ee552373>))
  (or (lsp--filter-clients (-andfn #'lsp--matching-clients\? #'lsp--server-binary-present\?)) (not (memq +lsp-prompt-to-install-server '(nil quiet))))
  (if (or (lsp--filter-clients (-andfn #'lsp--matching-clients\? #'lsp--server-binary-present\?)) (not (memq +lsp-prompt-to-install-server '(nil quiet)))) (apply fn args) (let ((doom-debug-p (or doom-debug-p (not (eq +lsp-prompt-to-install-server 'quiet))))) (doom-shut-up-a #'lsp--info "No language server available for %S" major-mode)))
  (progn (require 'lsp-mode) (lsp--require-packages) (if (or (lsp--filter-clients (-andfn #'lsp--matching-clients\? #'lsp--server-binary-present\?)) (not (memq +lsp-prompt-to-install-server '(nil quiet)))) (apply fn args) (let ((doom-debug-p (or doom-debug-p (not (eq +lsp-prompt-to-install-server ...))))) (doom-shut-up-a #'lsp--info "No language server available for %S" major-mode))))
  (if (buffer-file-name) (progn (require 'lsp-mode) (lsp--require-packages) (if (or (lsp--filter-clients (-andfn #'lsp--matching-clients\? #'lsp--server-binary-present\?)) (not (memq +lsp-prompt-to-install-server '(nil quiet)))) (apply fn args) (let ((doom-debug-p (or doom-debug-p (not ...)))) (doom-shut-up-a #'lsp--info "No language server available for %S" major-mode)))))
  +lsp-dont-prompt-to-install-servers-maybe-a(#f(compiled-function (&optional arg) "Entry point for the server startup.\nWhen ARG is t the lsp mode will start new language server even if\nthere is language server which can handle current language. When\nARG is nil current file will be opened in multi folder language\nserver if there is such. When `lsp' is called with prefix\nargument ask the user to select which language server to start." (interactive "P") #<bytecode 0x5284d49df32ef37>) nil)
  apply(+lsp-dont-prompt-to-install-servers-maybe-a #f(compiled-function (&optional arg) "Entry point for the server startup.\nWhen ARG is t the lsp mode will start new language server even if\nthere is language server which can handle current language. When\nARG is nil current file will be opened in multi folder language\nserver if there is such. When `lsp' is called with prefix\nargument ask the user to select which language server to start." (interactive "P") #<bytecode 0x5284d49df32ef37>) nil)
  lsp(nil)
  funcall-interactively(lsp nil)
  command-execute(lsp record)
  counsel-M-x-action("lsp")
  ivy-call()
  ivy-read("M-x " ("toggle-debug-on-error" "lsp" "lsp-dart-run" "dart-mode" "flutter-run" "dap-debug" "dap-breakpoint-add" "cd" "5x5" "amx" "arp" "dbx" "dig" "erc" "ert" "eww" "ftp" "gdb" "irc" "jdb" "man" "mpc" "pdb" "pwd" "rsh" "sdb" "xdb" "calc" "diff" "dirs" "ffap" "gnus" "grep" "help" "ielm" "info" "life" "lsp!" "mail" "mpuz" "ping" "pong" "talk" "term" "undo" "yank" "zone" "align" "chmod" "cider" ...) :predicate counsel--M-x-externs-predicate :require-match t :history counsel-M-x-history :action counsel-M-x-action :keymap (keymap (67108908 . counsel--info-lookup-symbol) (67108910 . counsel-find-symbol)) :initial-input nil :caller counsel-M-x)
  counsel-M-x()
  funcall-interactively(counsel-M-x)
  command-execute(counsel-M-x)

**Comment by ericdallo** [comment] 2022-01-01 17:06
> both two config should not take effect lsp-dart dap, right?

yes

> @ericdallo , can i disable native comp for doom? because that maybe not suitable for debug issue.

I think you can but I don't see any reason why do that. you can disable with a flag on packages.el I think

**Comment by ericdallo** [comment] 2022-01-01 17:57
@zw963 I just fixed my config and opened a issue regarding a PR fixing the issue on doom-emacs here: https://github.com/hlissner/doom-emacs/pull/5945, you can use my config again, I removed the pin which should work now.

**Comment by zw963** [comment] 2022-01-01 18:57
> @zw963 I just fixed my config and opened a issue regarding a PR fixing the issue on doom-emacs here: [hlissner/doom-emacs#5945](https://github.com/hlissner/doom-emacs/pull/5945), you can use my config again, I removed the pin which should work now.

okay, sorry, need to restart my OS, don't know why, `flutter run` very slowly.
