### ISSUE TITLE
JSON parse error when running dap-debug

### ISSUE THREAD

**Issue by siraben** [emacs-lsp/lsp-dart#87] opened 2021-01-08 13:44 UTC
**Describe the bug**
I'm unable to start a debug session with dap-mode, after running `M-x dap-debug` I get the following message.

```
error in process filter: End of file while parsing JSON: "premature end of input", "<string>", 1, 1024, 1024 [2 times]
```

**To Reproduce**
`M-x dap-debug`

**Version**
```
[LSP Dart] 1.17.11 (package: 20201206.1725) at 2021.01.08 @ Emacs 28.0.50
[Dart SDK] Dart SDK version: 2.10.4 (stable) (Wed Nov 11 13:35:58 2020 +0100) on "macos_x64"
```

**Comment by ericdallo** [comment] 2021-01-08 14:00
@siraben did you run `dap-dart-setup` before?

**Comment by siraben** [comment] 2021-01-08 14:03
@ericdallo yes.

**Comment by siraben** [comment] 2021-01-08 14:03
It was working before but has stopped working, not sure why.

**Comment by ericdallo** [comment] 2021-01-08 14:05
Ok, maybe some flutter/dart update broke that, could you <bkd>M-x</kbd> `toggle-debug-on-error` and reproduce the issue again, then paste the stacktrace here?

**Comment by siraben** [comment] 2021-01-08 14:10
Weird, I ran M-x `toggle-debug-on-error` then M-x `dap-debug`, but no stacktrace was produced.

**Comment by ericdallo** [comment] 2021-01-08 14:12
Probably because is not a elisp raw error, it's from parsing the json on dap buffer, @yyoncho do you know how to debug that?

**Comment by yyoncho** [comment] 2021-01-08 21:42
Might be similar to https://github.com/emacs-lsp/lsp-mode/issues/2375 What you can do is to wrap the debugger and see what exactly it is receiving.

**Comment by siraben** [comment] 2021-01-09 06:27
> Might be similar to https://github.com/emacs-lsp/lsp-mode/issues/2375 What you can do is to wrap the debugger and see what exactly it is receiving. 

How would I wrap the debugger?

**Comment by zheylmun** [comment] 2022-01-05 02:47
Did you ever get anywhere with this @siraben?
I'm seeing the same error and am also not clear on how to wrap the debugger as @yyoncho suggests.

**Comment by siraben** [comment] 2022-01-05 03:40
@zheylmun I have not programmed in Dart for a while so haven't tested the issue.

**Comment by ericdallo** [comment] 2022-01-05 12:51
Could you both test with latest lsp-dart released this week and confirm this is still happening?

**Comment by jvliwanag** [comment] 2022-06-29 04:29
Might be similar to what I reported here - https://github.com/emacs-lsp/lsp-dart/issues/163#issuecomment-1169519435

**Comment by ericdallo** [comment] 2022-10-31 00:05
This should be fixed after https://github.com/emacs-lsp/lsp-dart/pull/165

**Closed by ericdallo** 2022-10-31 00:05 UTC
