### ISSUE TITLE
Emacs stuck with large files.

### ISSUE THREAD

**Issue by gnumonk** [emacs-lsp/lsp-dart#39] opened 2020-07-03 13:09 UTC
**Describe the bug**
While opening large file lsp-dart/emacs get stuck

**To Reproduce**
1) Create flutter project 
2) Copy and Paste file in main.dart.
3) Try to import "import 'dart/ui' 

**Expected behavior**
Emacs should not stuck and lsp dart should be able to handle multiple LSP connections.

**Version**
[LSP Dart] 1.12.6 (package: 20200630.2233) at 2020.07.03 @ Emacs 26.2
[Dart SDK] Dart VM version: 2.9.0-18.0.dev.flutter-2ec47ad273 (be) (Thu Jun 25 00:20:31 2020 +0000) on "macos_x64"

**Comment by gnumonk** [comment] 2020-07-03 13:12
[backtrace.txt](https://github.com/emacs-lsp/lsp-dart/files/4869848/backtrace.txt)

[analyticspage_dart.txt](https://github.com/emacs-lsp/lsp-dart/files/4869857/analyticspage_dart.txt)

**Comment by ericdallo** [comment] 2020-07-03 14:25
@gnumonk Thanks for the report, it seems to be a bug with `lsp-dart-flutter-widget-guide-lines`, you can temporarily disable it with `(setq lsp-dart-flutter-widget-guides nil)`
Meanwhile, I'll investigate the bug

**Comment by ericdallo** [comment] 2020-07-04 18:50
The problem is not because of a huge file, it was a bug on the Flutter widget guide lines, it should be fixed on `lsp-dart` `1.12.7`, @gnumonk could you test it please?

**Closed by ericdallo** 2020-07-04 18:50 UTC

**Comment by gnumonk** [comment] 2020-07-05 12:25
Nope, Fix is not working. Please find enclosed backtrace. 

[backtrace.txt](https://github.com/emacs-lsp/lsp-dart/files/4874891/backtrace.txt)

**Comment by ericdallo** [comment] 2020-07-05 14:06
I think this could be some config in your emacs?
Your file works ok my emacs:
![image](https://user-images.githubusercontent.com/7820865/86534481-25be3c80-beaf-11ea-984f-a31685bad22e.png)

Please follow this debug template:

- [ ] Provide lsp-mode related package versions
:white_check_mark:  Provide the callstack when emacs locks up
- [ ] Make sure the issue reproduces with [lsp-start-plain.el](https://github.com/emacs-lsp/lsp-mode/blob/master/scripts/lsp-start-plain.el)
Maybe a CPU performance report can help too.

**Comment by ericdallo** [comment] 2020-07-06 14:01
@gnumonk, I was able to reproduce your problem with your file, now it seems to be a problem rendering the widget guides for a huge file, I'll need to try to improve the performance of the widget guides logic, if you want to work on that file without errors, temporary, you can `(setq lsp-dart-flutter-widget-guides nil)` or disabling `lsp-dart-flutter-widget-guides-mode`

**Comment by gnumonk** [comment] 2020-07-18 12:58
Any update on this?

**Comment by ericdallo** [comment] 2020-07-18 17:01
@gnumonk, I tested and the same behavior happens with VSCode, the problem is handling too many widget guides because of the huge file, in `lsp-dart`, it happens a `max-lisp-eval-depth`, I don't know how to improve that :/

You can disable that via `(setq lsp-dart-flutter-widget-guides nil)` or disabling `lsp-dart-flutter-widget-guides-mode`.

**Comment by yyoncho** [comment] 2020-07-18 17:38
@ericdallo you can try to show widget guides only for the visible part of the buffer

**Comment by ericdallo** [comment] 2020-07-18 17:55
This probably would help a lot, do you know how can I achieve that @yyoncho ?

**Comment by yyoncho** [comment] 2020-07-18 18:09
We do that for lenses in lsp-mode.el - We track what is visible and update the lenses when the visible part of the screen has changed.

**Comment by ericdallo** [comment] 2020-07-18 18:25
Looks good, I'll try to learn from it, thank you!

**Comment by ericdallo** [comment] 2020-07-18 22:06
@gnumonk I found a bug on the iteration of the widget guide lines build, I fixed it and the error does not happen anymore with your file, you can test it on `lsp-dart 1.13.3`.

@yyoncho I implemented the guide lines by window range, but I left in [this branch](https://github.com/emacs-lsp/lsp-dart/tree/widget-guides-only-on-window-range), I didn't pushed to master as the feature only show after `lsp-on-idle-hook` and it may be a strange UX. if we need on the future for performance issues, we can follow that idea, thanks!

**Comment by gnumonk** [comment] 2020-07-21 05:03
Thanks, @yyoncho, and @ericdallo for continuous effort.
