### ISSUE TITLE
Feature not supported before dart SDK 2.8.0

### ISSUE THREAD

**Issue by nrehm** [emacs-lsp/lsp-dart#34] opened 2020-05-29 20:18 UTC
Currently when using lsp-dart-show-flutter-outline the error 
Feature not supported before dart SDK 2.8.0 
appears.

Dart VM version: 2.8.2 (stable) (Unknown timestamp) on "linux_x64"
[LSP Dart] 1.8.0 at 2020.05.29 @ Emacs 26.3 <- tested with 2.11 too same error.

Cant pinpoint why tested on Linux & MacOs

**Comment by ericdallo** [comment] 2020-05-29 20:20
Thanks for the report, I recently refactored that and I thought that I added some tests for it, I'll check it

**Comment by ericdallo** [comment] 2020-05-29 20:21
Could you test it again with an updated `lsp-dart` version? currently `lsp-dart` is on `1.11.7` version

**Comment by nrehm** [comment] 2020-05-29 20:24
[LSP Dart] 1.11.8 at 2020.05.29 @ Emacs 26.3
apply: Feature not supported before dart SDK 2.8.0

Can i somehow debug what dart version emacs sees?

**Comment by ericdallo** [comment] 2020-05-29 20:28
Yes, try <kbd>M-x</kbd> `(lsp-dart-get-sdk-dir)`

**Comment by nrehm** [comment] 2020-05-29 20:35
![image](https://user-images.githubusercontent.com/207529/83303038-afb61e00-a1fc-11ea-9ad2-93d8e6e99d55.png)

same with (lsp-dart-get-sdk-dir) running doom emacs

**Comment by ericdallo** [comment] 2020-05-29 21:11
sorry, I mean <kbd>M-x</kbd> `eval-expression` `(lsp-dart-get-sdk-dir) `

**Comment by nrehm** [comment] 2020-05-29 21:24
Symbol’s value as variable is void: lsp-dart-get-sdk-dir

**Comment by nrehm** [comment] 2020-05-29 21:33
(lsp-dart--get-version) returns 2.8.2 :

**Comment by ericdallo** [comment] 2020-05-29 22:01
That's odd, I reproduced a test for this exact behavior and could not reproduce that:

[lsp-dart-utils-test.el](https://github.com/emacs-lsp/lsp-dart/blob/master/test/lsp-dart-utils-test.el)
```elisp
(ert-deftest lsp-dart-version-at-least-p--h-test ()
  (with-mock
    (mock (lsp-dart--get-dart-version) => "2.8.2")
    (should (lsp-dart-version-at-least-p "2.8.0"))
    (lsp-dart-assert-sdk-min-version "2.8.0")))
```

**Comment by nrehm** [comment] 2020-05-30 06:03
For some reason my installation does not see those two functions.

Debugger entered--Lisp error: (cl-assertion-failed ((string-prefix-p version (lsp-dart--get-dart-version)) "Feature not supported before dart SDK %s" "2.8.0" "2.8.2"))
  cl--assertion-failed((string-prefix-p version (lsp-dart--get-dart-version)) "Feature not supported before dart SDK %s" ("2.8.0" "2.8.2") nil)
  lsp-dart--assert-sdk-min-version("2.8.0")
  lsp-dart-show-outline(nil)
  funcall-interactively(lsp-dart-show-outline nil)
  call-interactively(lsp-dart-show-outline record nil)
  command-execute(lsp-dart-show-outline record)
  counsel-M-x-action("lsp-dart-show-outline")
  ivy-call()
  ivy-read("M-x " ("lsp-dart-run-test-file" "eval-expression" "lsp-treemacs-errors-list" "lsp-describe-session" "lsp-dart-show-flutter-outline" "lsp-dart-version" "flutter-run-or-hot-reload" "poetry-venv-toggle" "lsp-install-server" "lsp" "poetry" "lsp-rust-analyzer-run" "cd" "5x5" "amx" "arp" "dbx" "dig" "erc" "ert" "eww" "ftp" "gdb" "irc" "jdb" "man" "mpc" "pdb" "pwd" "rsh" "sdb" "xdb" "calc" "diff" "dirs" "ffap" "gnus" "grep" "help" "ielm" "info" "life" "lsp!" "mail" "mpuz" "ping" "pong" "talk" "term" "undo" ...) :predicate #f(compiled-function (x) #<bytecode 0x113370d>) :require-match t :history counsel-M-x-history :action counsel-M-x-action :keymap (keymap (67108908 . counsel--info-lookup-symbol) (67108910 . counsel-find-symbol)) :initial-input nil :caller counsel-M-x)
  counsel-M-x()
  funcall-interactively(counsel-M-x)
  call-interactively(counsel-M-x nil nil)
  command-execute(counsel-M-x)
  recursive-edit()
  debug(error (void-variable lsp-dart-get-sdk-dir))
  eval(lsp-dart-get-sdk-dir nil)
  #f(compiled-function (exp &optional insert-value no-truncate char-print-limit) "Evaluate EXP and print value in the echo area.\nWhen called interactively, read an Emacs Lisp expression and\nevaluate it.  Value is also consed on to front of the variable\n`values'.  Optional argument INSERT-VALUE non-nil (interactively,\nwith a non `-' prefix argument) means insert the result into the\ncurrent buffer instead of printing it in the echo area.\n\nNormally, this function truncates long output according to the\nvalue of the variables `eval-expression-print-length' and\n`eval-expression-print-level'.  When NO-TRUNCATE is\nnon-nil (interactively, with a prefix argument of zero), however,\nthere is no such truncation.\n\nIf the resulting value is an integer, and CHAR-PRINT-LIMIT is\nnon-nil (interactively, unless given a non-zero prefix argument)\nit will be printed in several additional formats (octal,\nhexadecimal, and character).  The character format is only used\nif the value is below CHAR-PRINT-LIMIT (interactively, if the\nprefix argument is -1 or the value doesn't exceed\n`eval-expression-print-maximum-character').\n\nRuns the hook `eval-expression-minibuffer-setup-hook' on entering the\nminibuffer.\n\nIf `eval-expression-debug-on-error' is non-nil, which is the default,\nthis command arranges for all errors to enter the debugger." (interactive #f(compiled-function () #<bytecode 0x194881d>)) #<bytecode 0x1cff53>)(lsp-dart-get-sdk-dir nil nil 127)
  apply(#f(compiled-function (exp &optional insert-value no-truncate char-print-limit) "Evaluate EXP and print value in the echo area.\nWhen called interactively, read an Emacs Lisp expression and\nevaluate it.  Value is also consed on to front of the variable\n`values'.  Optional argument INSERT-VALUE non-nil (interactively,\nwith a non `-' prefix argument) means insert the result into the\ncurrent buffer instead of printing it in the echo area.\n\nNormally, this function truncates long output according to the\nvalue of the variables `eval-expression-print-length' and\n`eval-expression-print-level'.  When NO-TRUNCATE is\nnon-nil (interactively, with a prefix argument of zero), however,\nthere is no such truncation.\n\nIf the resulting value is an integer, and CHAR-PRINT-LIMIT is\nnon-nil (interactively, unless given a non-zero prefix argument)\nit will be printed in several additional formats (octal,\nhexadecimal, and character).  The character format is only used\nif the value is below CHAR-PRINT-LIMIT (interactively, if the\nprefix argument is -1 or the value doesn't exceed\n`eval-expression-print-maximum-character').\n\nRuns the hook `eval-expression-minibuffer-setup-hook' on entering the\nminibuffer.\n\nIf `eval-expression-debug-on-error' is non-nil, which is the default,\nthis command arranges for all errors to enter the debugger." (interactive #f(compiled-function () #<bytecode 0x1802ef1>)) #<bytecode 0x1cff53>) (lsp-dart-get-sdk-dir nil nil 127))
   bbeval-expression(lsp-dart-get-sdk-dir nil nil 127)
  funcall-interactively(eval-expression lsp-dart-get-sdk-dir nil nil 127)
  call-interactively(eval-expression record nil)
  command-execute(eval-expression record)
  counsel-M-x-action("eval-expression")
  ivy-call()
  ivy-read("M-x " ("eval-expression" "lsp-treemacs-errors-list" "lsp-describe-session" "lsp-dart-show-flutter-outline" "lsp-dart-version" "flutter-run-or-hot-reload" "poetry-venv-toggle" "lsp-install-server" "lsp" "poetry" "lsp-rust-analyzer-run" "cd" "5x5" "amx" "arp" "dbx" "dig" "erc" "ert" "eww" "ftp" "gdb" "irc" "jdb" "man" "mpc" "pdb" "pwd" "rsh" "sdb" "xdb" "calc" "diff" "dirs" "ffap" "gnus" "grep" "help" "ielm" "info" "life" "lsp!" "mail" "mpuz" "ping" "pong" "talk" "term" "undo" "yank" ...) :predicate #f(compiled-function (x) #<bytecode 0x113370d>) :require-match t :history counsel-M-x-history :action counsel-M-x-action :keymap (keymap (67108908 . counsel--info-lookup-symbol) (67108910 . counsel-find-symbol)) :initial-input nil :caller counsel-M-x)
  counsel-M-x()
  funcall-interactively(counsel-M-x)
  call-interactively(counsel-M-x nil nil)
  command-execute(counsel-M-x)

**Comment by ericdallo** [comment] 2020-05-30 12:59
@nrehm Could you try to clean your `lsp-dart` byte-compiled files?
In doom-emacs, a `rm -r ~/.emacs.d/.local/straight/repos/lsp-dart` and a `doom sync` should fix, then restart Emacs and check if it happen again

**Comment by nrehm** [comment] 2020-05-30 14:29
Looks like i could clear it up.
The build directory for some reason did not setup correctly and incorrectly linked files.
Maybe through an older version of lsp-dart that currently gets pulled via doom sync.

Had to clear straight/build/lsp-dart and then refresh inside emacs.

Now emacs freezes when i try to wrap something :)

**Comment by ericdallo** [comment] 2020-05-30 14:36
Sorry, I didn't understand, the problem with `lsp-dart` was fixed?
I think for things like this you can try `doom build` and then restart emacs.

**Comment by lybeen** [comment] 2020-05-30 17:52
I encountered with the same problem, how to fix it ?

![image](https://user-images.githubusercontent.com/1678324/83335731-5542bd80-a2e1-11ea-8823-c428de71ee55.png)

seems i can not find the sdk dir

**Comment by ericdallo** [comment] 2020-05-30 18:09
you should run this command from a buffer of your project as said it [here](https://github.com/emacs-lsp/lsp-dart/issues/34#issuecomment-636194223).

**Comment by nrehm** [comment] 2020-05-30 18:10
@lybeen @ericdallo 
Currently when installing lsp-dart via doom emacs it pulls in v1.8.0 from the pkg repository (melpa?)
The outline feature is not part of this release?

![image](https://user-images.githubusercontent.com/207529/83336168-8c00df80-a2b1-11ea-9c4f-46ac390ac585.png)

What fixed it for me is manually go into ~/.emacs.d/.local/straight/repos/lsp-dart
git pull origin master and then ~/.emacs.d/bin/doom build

**Comment by ericdallo** [comment] 2020-05-30 18:22
Oh, doom-emacs in the package versions, I need to update the package version on doom-emacs, thanks for noticing it, I'll open a PR there.

**Comment by lybeen** [comment] 2020-05-30 18:26
> you should run this command from a buffer of your project as said it [here](https://github.com/emacs-lsp/lsp-dart/issues/34#issuecomment-636194223). Running in the doom `scratch` buffer won't work.

![image](https://user-images.githubusercontent.com/1678324/83336453-18c59080-a2e6-11ea-9f40-622ee02eec80.png)
i eval from my project, it seems without this function

**Comment by lybeen** [comment] 2020-05-30 18:29
@nrehm  i use the Vanilla Emacs 😭

**Comment by ericdallo** [comment] 2020-05-30 18:55
@lybeen, this is a function, not a command so you need to run <kbd>M-x</kbd> `eval-expression` `(lsp-dart-get-sdk-dir)`

PS: I'm implementing to show the dart SDK version too when running `lsp-dart-version`

**Comment by ericdallo** [comment] 2020-05-30 19:08
@nrehm https://github.com/hlissner/doom-emacs/pull/3259

**Comment by ericdallo** [comment] 2020-05-31 15:05
I'm closing this as we updated the version on doom-emacs

**Closed by ericdallo** 2020-05-31 15:05 UTC
Labels: need upstream
