### ISSUE TITLE
Completion Performance

### ISSUE THREAD

**Issue by nickenchev** [emacs-lsp/lsp-dart#3] opened 2020-04-13 18:32 UTC
**Describe the bug**
While typing inside a dart file, completions often take 1-2 seconds to return and freeze all input within the editor. When ```lsp-print-io``` is set to ```t```, completions takes 4, 5 seconds.

**To Reproduce**
Open main.dart in the sample application produced by flutter and start typing inside a method.

**Expected behavior**
No freezing during typing, or much more minimal. Not sure how these completion backends work, but it feels like heavy work is being done on the wrong thread.

**Logs**
***Messages***
LSP :: Connected to [dart_analysis_server:22228 status:starting].
LSP :: dart_analysis_server:22228 initialized successfully
Saving file /home/nenchev/Developer/projects/threadxchange/threadxchange/lib/main.dart...
Wrote /home/nenchev/Developer/projects/threadxchange/threadxchange/lib/main.dart

**lsp-log: dart_analysis_server**
After setting ```lsp-print-io``` to ```t```, the log produced in this buffer was 9.4MiB, after 1 or 2 completions only.
https://drive.google.com/open?id=1bD4FcaTc4nDGb6h_IMomo730_xkoBsGM

Running: GNU Emacs 27.0.90 (Build 1...)

**Comment by ericdallo** [comment] 2020-04-13 18:48
@nickenchev, there's an issue on Dart sdk [here](https://github.com/dart-lang/sdk/issues/40026) about the log size.

`lsp-print-io` really slows down the completion, it may be used only for debug reasons.

I had this problem too when I had emacs 26.3, after I updated to emacs 28, the problem was resolved, I think that's because emacs 27 added a native JSON parser and increased all LSPs performance with that. 
Are you using `company-capf` instead of `company-lsp`, I think it's the recommended for LSP.

**Comment by nickenchev** [comment] 2020-04-13 20:53
@ericdallo I was actually using the same the latest Emacs 28 git from Arch AUR, which is where I first noticed the issue. I realize that ```lsp-print-io``` causes a massive spike due to debug info, I don't normally keep that set, it was only for this issue report.

I'm not using capf, just company-lsp I believe. I'm not actually sure why I should use one over the other, though I did notice it as an optional package in the getting started guide.

**Comment by nickenchev** [comment] 2020-04-13 21:03
I just added: ```:init (add-to-list 'company-backends 'company-capf)``` to my lsp-mode configuration, and it has made a big difference in completion performance. The freezing is pretty much gone.
```
(use-package lsp-mode
  :straight t
  :init (add-to-list 'company-backends 'company-capf)
  :config
  (setq lsp-ui-doc-enable nil)
  :bind ("C-c d d" . 'lsp-ui-doc-show)
  :bind ("C-c d h" . 'lsp-ui-doc-hide)
  :commands lsp)
```

**Comment by ericdallo** [comment] 2020-04-13 21:08
Nice, good to know that, I'm using `company-capf` too, maybe that's why I can't reproduce this.

I'll certainly add this to the FAQ on README, thanks @nickenchev

**Comment by nickenchev** [comment] 2020-04-13 21:25
So I might have lied and exaggerated the improvement that made, it really did feel quicker when getting completions right after I made that switch. I'm still getting freezes as I type and completions are being returned. Is there anything else I should check?

> Use Emacs 27+ with native json support. In order to validate that you match this criteria do M-: (functionp 'json-serialize) RET. Benchmarks show that Emacs 27 is ~15 times faster than Emacs when using Elisp json parser implementation.

Evaluating this expression returns ```t``` so it appears to be ok.

**Comment by ericdallo** [comment] 2020-04-13 21:32
Odd, you can check my personal config [here](https://github.com/ericdallo/dotfiles/blob/master/emacs/.doom.d/config.el#L115-L120), but I don't think you need to change anything more...
![completion](https://user-images.githubusercontent.com/7820865/79163128-d935fa00-7db4-11ea-8328-3162e0c721e1.gif)

**Comment by ericdallo** [comment] 2020-04-13 21:33
@yyoncho do you know something more we can try?

**Comment by nickenchev** [comment] 2020-04-13 21:43
Honestly, my biggest takeaway there was that I need that "parrot" package.

**Comment by ericdallo** [comment] 2020-04-13 21:46
:p [parrot.el](https://github.com/jnc-nj/parrot)

**Comment by yyoncho** [comment] 2020-04-14 04:25
@nickenchev 

> Expected behavior
No freezing during typing, or much more minimal. Not sure how these completion backends work, but it feels like heavy work is being done on the wrong thread.

There is only one thread.

Other than that: 
0. Make sure you are using latest stuff on dart side.
1. Make sure that lsp-mode.el is byte-compiled using emacs 27+ which has native json parser.
2. After you ensure that follow the instructions at https://github.com/emacs-lsp/lsp-mode/#performance and also provide the data as described in https://github.com/emacs-lsp/lsp-mode/#reporting-performance-problems (make sure you do the benchmarks with lsp-print-io set to nil).

dart is the most challenging language server since sometimes the completion data may be more than 3mb. I think that one way to speed it up is to set `lsp-dart-suggest-from-unimported-libraries` to nil - I am not sure how much it will hurt usability. But in any case, if the performance data shows up issue we will reopen the discussion with emacs-devel about providing facilities for handling that much load(although I think the issue is most likely 1 will fix it).

**Comment by nickenchev** [comment] 2020-04-14 22:02
@yyoncho When you say there is only one thread, is that an emacs limitation? I don't have a deep understanding of the Emacs limitations.

**Comment by ericdallo** [comment] 2020-04-14 22:06
Yes @nickenchev

**Comment by freewebwithme** [comment] 2020-05-08 20:09
I have same issue in emacs 28 using spacemacs.

**Comment by yyoncho** [comment] 2020-05-08 20:19
@freewebwithme what do you get when you do M-x lsp-diagnose?

**Comment by freewebwithme** [comment] 2020-05-08 20:45
It says

Checking for Native JSON support: OK
Checking emacs version has `read-process-output-max': OK
Using company-capf: : OK
Check emacs supports `read-process-output-max': OK
Check `read-process-output-max' default has been changed from 4k: ERROR
Byte compiled against native json (recompile emacs if failing.): ERROR
`gc-cons-threshold' increased?: OK

**Comment by yyoncho** [comment] 2020-05-08 20:49
Delete lsp-mode. Change read-process-output-max.

**Comment by freewebwithme** [comment] 2020-05-08 21:04
where and how can I read-process-output-max to 1mb?

**Comment by freewebwithme** [comment] 2020-05-08 21:09
I found your message in gitter
(setq read-process-output-max (* 1024 1024))

**Comment by ericdallo** [comment] 2020-05-08 21:11
@freewebwithme I think `(setq read-process-output-max (* 1024 1024))` can handle it

**Comment by freewebwithme** [comment] 2020-05-08 21:21
Thanks I think it became little faster but I need some time to test.
Because it was fast when I first install lsp-dart.

**Comment by ericdallo** [comment] 2020-05-20 20:40
Closing this, we can reopen if the problem comes back

**Closed by ericdallo** 2020-05-20 20:40 UTC

**Comment by ericdallo** [comment] 2020-06-26 13:10
It seems to have a huge fix on that: https://github.com/dart-lang/sdk/issues/40026#issuecomment-650046508
