### ISSUE TITLE
Navigating to a souce file in Dart or Flutter SDK shows serveral 100k errors

### ISSUE THREAD

**Issue by zoechi** [emacs-lsp/lsp-dart#73] opened 2020-10-08 14:34 UTC
**Describe the bug**
When I navigate from a project Dart source file to a Flutter SDK file (for example to `Widget`),
I get 380k errors and I also can not navigate further from within a Flutter SDK file.
It looks like all errors are because no imports can be resolved.

It is the same behavior in Dart projects.

**Note**

**To Reproduce**
{populate}

**Expected behavior**
DartAnalyzer should be able to analyze the SDK itself and so should lsp-dart

**Screenshots**

**Version**
```
[LSP Dart] 1.17.6 (package: 20200510.2055) at 2020.10.08 @ Emacs 28.0.50
[Dart SDK] Dart SDK version: 2.10.0-136.0.dev (dev) (Wed Sep 16 13:30:26 2020 -0700) on "linux_x64"
```

**Comment by ericdallo** [comment] 2020-10-08 14:58
I think this is duplicate of https://github.com/emacs-lsp/lsp-dart/issues/74 right?

**Closed** 2021-08-29 14:18 UTC
